# Generated by Django 5.0.6 on 2024-06-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivoObligacion', models.CharField(max_length=20)),
                ('nitDeudor', models.CharField(max_length=20)),
                ('fechaCompromiso', models.DateTimeField()),
                ('estado', models.CharField(max_length=100)),
                ('descripcionCodigoCobro', models.CharField(max_length=200)),
                ('grabador', models.CharField(max_length=20)),
                ('valorPactado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=100)),
                ('valorRecaudo', models.CharField(max_length=100)),
                ('fechaPago', models.DateTimeField()),
            ],
        ),
    ]
