# Generated by Django 5.0.6 on 2024-06-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0002_alter_gestion_fechacompromiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='fechaPago',
            field=models.DateTimeField(null=True),
        ),
    ]
