# Generated by Django 5.0.6 on 2024-06-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0004_alter_pagos_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='cedula',
            field=models.CharField(max_length=200),
        ),
    ]
