# Generated by Django 5.0.6 on 2024-06-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0005_alter_pagos_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='fechaGestion',
            field=models.DateTimeField(null=True),
        ),
    ]
