# Generated by Django 5.0.6 on 2024-06-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0006_gestion_fechagestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestion',
            name='fechaCompromiso',
        ),
    ]
