# Generated by Django 5.0.6 on 2024-06-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0007_remove_gestion_fechacompromiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='valorRecaudo',
            field=models.CharField(max_length=200),
        ),
    ]
