# Generated by Django 5.0.6 on 2024-06-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0008_alter_pagos_valorrecaudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='valorRecaudo',
            field=models.IntegerField(),
        ),
    ]
